"use client";

import { useEffect, useState } from "react";
import { ErrorState, LoadingState } from "@/components/LoadingState";
import { StatusPill } from "@/components/StatusPill";
import { api } from "@/lib/api";
import type { SettingsView } from "@/lib/types";

export function SettingsPageClient({ candidateId }: { candidateId: string }) {
  const [settings, setSettings] = useState<SettingsView | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { api.settings(candidateId).then(setSettings).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Settings are unavailable.")); }, [candidateId]);
  async function mode(automation_mode: SettingsView["automation_mode"]) { if (automation_mode === "autonomous" && !globalThis.confirm("Enable autonomous mode only after all displayed blockers are resolved?")) return; setSaving(true); setError(null); try { setSettings(await api.updateSettings({ candidate_id: candidateId, automation_mode })); } catch (reason) { setError(reason instanceof Error ? reason.message : "The backend denied this setting."); } finally { setSaving(false); } }
  async function stop() { if (!globalThis.confirm("Stop all new submissions immediately?")) return; setSettings(await api.emergencyStop(candidateId)); }
  return <div className="page-wrap"><header className="page-header"><div><p className="eyebrow">Candidate automation policy</p><h1>Settings</h1></div><p>Backend readiness is authoritative. The interface cannot enable autonomy while any blocker remains.</p></header>{error ? <ErrorState message={error} /> : null}{!settings ? <LoadingState label="Loading automation controls" /> : <div className="settings-grid"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Current mode</p><h2>{settings.automation_mode.replaceAll("_", " ")}</h2></div><StatusPill status={settings.emergency_stopped ? "BLOCKED" : "READY"} /></div><div className="mode-grid">{(["disabled", "dry_run", "approval_required", "autonomous"] as const).map((item) => <button key={item} className={`button ${settings.automation_mode === item ? "primary" : "secondary"}`} disabled={saving || (item === "autonomous" && settings.autonomy_blockers.length > 0)} onClick={() => void mode(item)}>{item.replaceAll("_", " ")}</button>)}</div>{settings.autonomy_blockers.length ? <><h3>Autonomy blockers</h3><ul className="blocker-list">{settings.autonomy_blockers.map((blocker) => <li key={blocker}>{blocker.replaceAll("_", " ")}</li>)}</ul></> : <p className="form-message success">All autonomous-mode prerequisites are recorded.</p>}</section><section className="panel"><p className="eyebrow">Rate limits</p><h2>Application boundaries</h2><dl className="compact-metadata"><div><dt>Daily</dt><dd>{settings.maximum_applications_per_day}</dd></div><div><dt>Weekly</dt><dd>{settings.maximum_applications_per_week}</dd></div><div><dt>Per company / 30 days</dt><dd>{settings.maximum_applications_per_company_30_days}</dd></div></dl><p>Tested ATS: {settings.tested_ats_adapters.join(", ") || "None"}</p></section><section className="panel emergency-panel"><p className="eyebrow">Immediate control</p><h2>Emergency stop</h2><p>Prevents all new submission authorizations while preserving in-progress state and audit history.</p><button className="button danger" onClick={() => void stop()}>Activate emergency stop</button></section></div>}</div>;
}
