"""initial milestone 1 schema

Revision ID: 01b5a2f6e718
Revises:
Create Date: 2026-08-04 18:53:45.233607
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01b5a2f6e718"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_global_job_source_id"),
    )
    op.create_index(op.f("ix_global_jobs_company"), "global_jobs", ["company"], unique=False)
    op.create_index(op.f("ix_global_jobs_title"), "global_jobs", ["title"], unique=False)
    op.create_table(
        "candidate_job_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("scoring_version", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.JSON(), nullable=False),
        sa.Column("meets_threshold", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["global_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "job_id", "scoring_version", name="uq_candidate_job_score"
        ),
    )
    op.create_index(
        op.f("ix_candidate_job_scores_candidate_id"),
        "candidate_job_scores",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_job_scores_job_id"), "candidate_job_scores", ["job_id"], unique=False
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("score_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "DISCOVERED",
                "NORMALIZED",
                "SECURITY_CHECK",
                "CLASSIFIED",
                "SCORED",
                "SKIPPED",
                "SHORTLISTED",
                "CANDIDATE_SNAPSHOT_CREATED",
                "MATERIALS_GENERATING",
                "MATERIALS_READY",
                "REVIEW_PENDING",
                "REVIEW_FAILED",
                "APPLICATION_STARTED",
                "FORM_FILLING",
                "HUMAN_ACTION_REQUIRED",
                "FINAL_VALIDATION",
                "READY_TO_SUBMIT",
                "SUBMITTING",
                "SUBMITTED",
                "CONFIRMED",
                "FAILED_RETRYABLE",
                "FAILED_FINAL",
                "CLOSED",
                "REJECTED",
                "INTERVIEW",
                "OFFER",
                "WITHDRAWN",
                name="applicationstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "PENDING",
                "SKIPPED",
                "SUBMITTED",
                "REJECTED",
                "WITHDRAWN",
                name="applicationoutcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["global_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["candidate_job_scores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "job_id", name="uq_candidate_application_job"),
    )
    op.create_index(
        op.f("ix_applications_candidate_id"), "applications", ["candidate_id"], unique=False
    )
    op.create_index(op.f("ix_applications_job_id"), "applications", ["job_id"], unique=False)
    op.create_table(
        "agent_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("PASS", "FAIL", "HUMAN_REVIEW", name="reviewdecision", native_enum=False),
            nullable=False,
        ),
        sa.Column("semantic_passed", sa.Boolean(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_reviews_application_id"), "agent_reviews", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_reviews_candidate_id"), "agent_reviews", ["candidate_id"], unique=False
    )
    op.create_table(
        "application_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("question_key", sa.String(length=255), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("approved_source_key", sa.String(length=255), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "application_id", "question_key", name="uq_application_answer"
        ),
    )
    op.create_index(
        op.f("ix_application_answers_application_id"),
        "application_answers",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_answers_candidate_id"),
        "application_answers",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("CV", "COVER_LETTER", "OTHER", name="documentkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "application_id", "kind", "version", name="uq_application_document"
        ),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_candidate_id"),
        "application_documents",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "application_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "DISCOVERED",
                "NORMALIZED",
                "SECURITY_CHECK",
                "CLASSIFIED",
                "SCORED",
                "SKIPPED",
                "SHORTLISTED",
                "CANDIDATE_SNAPSHOT_CREATED",
                "MATERIALS_GENERATING",
                "MATERIALS_READY",
                "REVIEW_PENDING",
                "REVIEW_FAILED",
                "APPLICATION_STARTED",
                "FORM_FILLING",
                "HUMAN_ACTION_REQUIRED",
                "FINAL_VALIDATION",
                "READY_TO_SUBMIT",
                "SUBMITTING",
                "SUBMITTED",
                "CONFIRMED",
                "FAILED_RETRYABLE",
                "FAILED_FINAL",
                "CLOSED",
                "REJECTED",
                "INTERVIEW",
                "OFFER",
                "WITHDRAWN",
                name="applicationstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "DISCOVERED",
                "NORMALIZED",
                "SECURITY_CHECK",
                "CLASSIFIED",
                "SCORED",
                "SKIPPED",
                "SHORTLISTED",
                "CANDIDATE_SNAPSHOT_CREATED",
                "MATERIALS_GENERATING",
                "MATERIALS_READY",
                "REVIEW_PENDING",
                "REVIEW_FAILED",
                "APPLICATION_STARTED",
                "FORM_FILLING",
                "HUMAN_ACTION_REQUIRED",
                "FINAL_VALIDATION",
                "READY_TO_SUBMIT",
                "SUBMITTING",
                "SUBMITTED",
                "CONFIRMED",
                "FAILED_RETRYABLE",
                "FAILED_FINAL",
                "CLOSED",
                "REJECTED",
                "INTERVIEW",
                "OFFER",
                "WITHDRAWN",
                name="applicationstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "application_id", "idempotency_key", name="uq_application_event_key"
        ),
    )
    op.create_index(
        op.f("ix_application_events_application_id"),
        "application_events",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_events_candidate_id"),
        "application_events",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        "ix_application_events_timeline",
        "application_events",
        ["candidate_id", "application_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "browser_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=True),
        sa.Column("external_session_ref", sa.String(length=255), nullable=True),
        sa.Column("stopped_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_browser_sessions_application_id"),
        "browser_sessions",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_browser_sessions_candidate_id"), "browser_sessions", ["candidate_id"], unique=False
    )
    op.create_table(
        "human_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum("APPROVE", "DENY", "EDIT", "PAUSE", name="humanactionkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_actions_application_id"), "human_actions", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_actions_candidate_id"), "human_actions", ["candidate_id"], unique=False
    )
    op.create_table(
        "interviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interviews_application_id"), "interviews", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_interviews_candidate_id"), "interviews", ["candidate_id"], unique=False
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("base_compensation", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("offered_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_application_id"), "offers", ["application_id"], unique=False)
    op.create_index(op.f("ix_offers_candidate_id"), "offers", ["candidate_id"], unique=False)
    op.create_table(
        "security_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_events_application_id"),
        "security_events",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_events_candidate_id"), "security_events", ["candidate_id"], unique=False
    )
    op.create_index(
        "ix_security_events_candidate_time",
        "security_events",
        ["candidate_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_security_events_candidate_time", table_name="security_events")
    op.drop_index(op.f("ix_security_events_candidate_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_application_id"), table_name="security_events")
    op.drop_table("security_events")
    op.drop_index(op.f("ix_offers_candidate_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_application_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_interviews_candidate_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_application_id"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_human_actions_candidate_id"), table_name="human_actions")
    op.drop_index(op.f("ix_human_actions_application_id"), table_name="human_actions")
    op.drop_table("human_actions")
    op.drop_index(op.f("ix_browser_sessions_candidate_id"), table_name="browser_sessions")
    op.drop_index(op.f("ix_browser_sessions_application_id"), table_name="browser_sessions")
    op.drop_table("browser_sessions")
    op.drop_index("ix_application_events_timeline", table_name="application_events")
    op.drop_index(op.f("ix_application_events_candidate_id"), table_name="application_events")
    op.drop_index(op.f("ix_application_events_application_id"), table_name="application_events")
    op.drop_table("application_events")
    op.drop_index(op.f("ix_application_documents_candidate_id"), table_name="application_documents")
    op.drop_index(
        op.f("ix_application_documents_application_id"), table_name="application_documents"
    )
    op.drop_table("application_documents")
    op.drop_index(op.f("ix_application_answers_candidate_id"), table_name="application_answers")
    op.drop_index(op.f("ix_application_answers_application_id"), table_name="application_answers")
    op.drop_table("application_answers")
    op.drop_index(op.f("ix_agent_reviews_candidate_id"), table_name="agent_reviews")
    op.drop_index(op.f("ix_agent_reviews_application_id"), table_name="agent_reviews")
    op.drop_table("agent_reviews")
    op.drop_index(op.f("ix_applications_job_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_candidate_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_candidate_job_scores_job_id"), table_name="candidate_job_scores")
    op.drop_index(op.f("ix_candidate_job_scores_candidate_id"), table_name="candidate_job_scores")
    op.drop_table("candidate_job_scores")
    op.drop_index(op.f("ix_global_jobs_title"), table_name="global_jobs")
    op.drop_index(op.f("ix_global_jobs_company"), table_name="global_jobs")
    op.drop_table("global_jobs")
    # ### end Alembic commands ###
